version: '3'
services:
  app:
    build: .
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:cris123@host.docker.internal:3306/centrolmovil
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
